version: 43.0.9
pageUuid: 3e22f93a-20a6-11ee-93ff-af55b0ccc0ec
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  preloadedAppJavaScript: |
    window.deleteRowCheck = () => {
      return ""
    }
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 3.2.2
  experimentalDataTabEnabled: true
