version: 43.0.9
pageUuid: a023112e-fa04-11ed-b429-4f766077e95d
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
      runtimeV2OptOut: false
  version: 2.121.10
  experimentalDataTabEnabled: true
