return [
  {
    id: 0,
    firstName: "Chic",
    lastName: "Footitt",
    email: "chic.footitt@yahoo.com",
    website: "https://chic.footitt.com",
    text: "Nulla sit amet nibh at augue facilisis viverra quis id dui. Nullam mattis ultricies metus. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris",
    role: "Viewer",
    teams: ["Workplace", "Infrastructure"],
    enabled: true,
    createdAt: "2023-01-16T23:40:20.385Z",
  },
  {
    id: 1,
    firstName: "Kenton",
    lastName: "Worling",
    email: "kentonworling@yahoo.com",
    website: "https://kenton.worling.com",
    text: "Duis viverra elementum ante, placerat sollicitudin ipsum laoreet nec.. Suspendisse et lacus augue. Nullam mattis ultricies metus. Etiam bibendum auctor aliquet. Proin scelerisque molestie lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet metus velit. Phasellus bibendum luctus dignissim. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris",
    role: "Viewer",
    teams: ["Workplace"],
    enabled: false,
    createdAt: "2021-12-24T23:40:20.385Z",
  },
  {
    id: 2,
    firstName: "Evelina",
    lastName: "Fender",
    email: "efender@outlook.com",
    website: "https://evelina.fender.com",
    text: "Nulla sit amet nibh at augue facilisis viverra quis id dui. Suspendisse et lacus augue. Donec in lorem a dolor placerat gravida. Sed eu mollis felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis viverra elementum ante, placerat sollicitudin ipsum laoreet nec.. Etiam bibendum auctor aliquet. Nullam lacinia nec risus et pharetra",
    role: "Editor",
    teams: ["Product", "Sales"],
    enabled: true,
    createdAt: "2022-01-03T23:40:20.385Z",
  },
  {
    id: 3,
    firstName: "Lexis",
    lastName: "Speers",
    email: "lexisspeers@icloud.com",
    website: "https://lexis.speers.com",
    text: "Donec in lorem a dolor placerat gravida. Suspendisse et lacus augue. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris. Proin scelerisque molestie lacinia. Sed eu mollis felis. Nullam mattis ultricies metus",
    role: "Admin",
    teams: ["Infrastructure", "Design"],
    enabled: true,
    createdAt: "2022-12-13T23:40:20.385Z",
  },
  {
    id: 4,
    firstName: "Kenton",
    lastName: "Antonioni",
    email: "kenton.antonioni@icloud.com",
    website: "https://kenton.antonioni.com",
    text: "Etiam bibendum auctor aliquet. Nullam mattis ultricies metus. Ut ullamcorper gravida pretium. Suspendisse et lacus augue. Vivamus sit amet metus velit. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris. Nullam lacinia nec risus et pharetra. Proin scelerisque molestie lacinia",
    role: "Admin",
    teams: ["Success", "Recruiting", "Data"],
    enabled: true,
    createdAt: "2022-04-15T23:40:20.385Z",
  },
  {
    id: 5,
    firstName: "Nanon",
    lastName: "Stit",
    email: "nanonstit@gmail.com",
    website: "https://nanon.stit.com",
    text: "Sed eu mollis felis. Nulla sit amet nibh at augue facilisis viverra quis id dui. Vivamus sit amet metus velit. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris",
    role: "Editor",
    teams: ["Data"],
    enabled: false,
    createdAt: "2022-10-14T23:40:20.385Z",
  },
  {
    id: 6,
    firstName: "Shaylah",
    lastName: "Aynscombe",
    email: "shaylahaynscombe@outlook.com",
    website: "https://shaylah.aynscombe.com",
    text: "Phasellus bibendum luctus dignissim. Donec in lorem a dolor placerat gravida. Nullam mattis ultricies metus. Suspendisse et lacus augue. Proin scelerisque molestie lacinia",
    role: "Viewer",
    teams: ["Infrastructure"],
    enabled: true,
    createdAt: "2022-01-16T23:40:20.385Z",
  },
  {
    id: 7,
    firstName: "Lexis",
    lastName: "Scad",
    email: "lscad@gmail.com",
    website: "https://lexis.scad.com",
    text: "Nullam mattis ultricies metus",
    role: "Editor",
    teams: ["Finance", "Support", "Product"],
    enabled: true,
    createdAt: "2023-04-22T23:40:20.386Z",
  },
  {
    id: 8,
    firstName: "Joan",
    lastName: "Speers",
    email: "jspeers@outlook.com",
    website: "https://joan.speers.com",
    text: "Proin scelerisque molestie lacinia. Ut ullamcorper gravida pretium. Phasellus non nibh ut enim mattis malesuada. Nullam mattis ultricies metus. Suspendisse et lacus augue. Nullam lacinia nec risus et pharetra",
    role: "Editor",
    teams: ["Infrastructure", "Finance"],
    enabled: true,
    createdAt: "2022-08-14T23:40:20.386Z",
  },
  {
    id: 9,
    firstName: "Cassandre",
    lastName: "Ansteys",
    email: "c.ansteys@yahoo.com",
    website: "https://cassandre.ansteys.com",
    text: "Vivamus sit amet metus velit. Suspendisse et lacus augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet nibh at augue facilisis viverra quis id dui. Etiam bibendum auctor aliquet. Sed eu mollis felis. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris. Proin scelerisque molestie lacinia. Ut ullamcorper gravida pretium",
    role: "Admin",
    teams: ["Recruiting", "Success", "Infrastructure"],
    enabled: false,
    createdAt: "2022-03-20T23:40:20.386Z",
  },
  {
    id: 10,
    firstName: "Amberly",
    lastName: "Fender",
    email: "amberlyfender@outlook.com",
    website: "https://amberly.fender.com",
    text: "Donec in lorem a dolor placerat gravida",
    role: "Editor",
    teams: ["Engineering", "Sales"],
    enabled: true,
    createdAt: "2023-04-24T23:40:20.386Z",
  },
  {
    id: 11,
    firstName: "Di",
    lastName: "Scad",
    email: "d.scad@yahoo.com",
    website: "https://di.scad.com",
    text: "Phasellus non nibh ut enim mattis malesuada. Ut ullamcorper gravida pretium. Suspendisse et lacus augue",
    role: "Admin",
    teams: ["Design", "Recruiting"],
    enabled: false,
    createdAt: "2022-05-06T23:40:20.386Z",
  },
  {
    id: 12,
    firstName: "Clim",
    lastName: "Spratt",
    email: "c.spratt@outlook.com",
    website: "https://clim.spratt.com",
    text: "Ut ullamcorper gravida pretium. Duis viverra elementum ante, placerat sollicitudin ipsum laoreet nec.. Phasellus bibendum luctus dignissim. Nulla sit amet nibh at augue facilisis viverra quis id dui. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris. Nullam mattis ultricies metus. Phasellus non nibh ut enim mattis malesuada",
    role: "Admin",
    teams: ["Marketing", "Sales"],
    enabled: false,
    createdAt: "2022-08-18T23:40:20.386Z",
  },
  {
    id: 13,
    firstName: "Mildred",
    lastName: "MacAskie",
    email: "mildred.macaskie@yahoo.com",
    website: "https://mildred.macaskie.com",
    text: "Nulla sit amet nibh at augue facilisis viverra quis id dui. Phasellus non nibh ut enim mattis malesuada. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris",
    role: "Admin",
    teams: ["Finance", "Sales", "Marketing"],
    enabled: false,
    createdAt: "2022-05-07T23:40:20.386Z",
  },
  {
    id: 14,
    firstName: "Clim",
    lastName: "Speers",
    email: "c.speers@yahoo.com",
    website: "https://clim.speers.com",
    text: "Suspendisse et lacus augue. Donec eros lorem, egestas vitae aliquam quis, rutrum a mauris. Nulla sit amet nibh at augue facilisis viverra quis id dui. Nullam lacinia nec risus et pharetra. Ut ullamcorper gravida pretium",
    role: "Editor",
    teams: ["Product", "Marketing"],
    enabled: true,
    createdAt: "2023-03-06T23:40:20.386Z",
  }
];
