id: ApplicationSearchInput
type: widget
subtype: TextInputWidget2
template:
  ordered:
    - spellCheck: false
    - readOnly: false
    - iconAfter: ''
    - showCharacterCount: false
    - autoComplete: false
    - maxLength: null
    - hidden: false
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - textBefore: ''
    - validationMessage: ''
    - textAfter: ''
    - showInEditor: false
    - _defaultValue: ''
    - showClear: false
    - pattern: ''
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: ''
    - labelCaption: ''
    - labelWidth: '33'
    - autoFill: ''
    - placeholder: Enter value
    - _disclosedFields:
        array: []
    - label: Search by app name
    - _validate: false
    - labelWidthUnit: '%'
    - invalid: false
    - iconBefore: ''
    - minLength: null
    - inputTooltip: ''
    - events:
        ordered: []
    - autoCapitalize: none
    - loading: false
    - disabled: false
    - labelPosition: top
    - labelWrap: false
    - maintainSpaceWhenHidden: false
    - required: false
style:
  ordered: []
position2:
  position2:
    container: container3
    subcontainer: 58fd5
    height: 1
    width: 4
createdAt: 2022-06-22T20:47:11.176Z
