version: 43.0.9
pageUuid: d87c0f4e-b756-11ed-8ade-57ebb093236e
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      displaySetting:
        object:
          landscapeMode: false
          tabletMode: false
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
      runtimeV2OptOut: false
  version: 2.117.7
