version: 43.0.9
pageUuid: 3e3a9536-1cd7-11ee-ad68-5bf1be59e185
appTemplate:
  appMaxWidth: 100%
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 3.2.2
  experimentalDataTabEnabled: true
