version: 43.0.9
pageUuid: 3fca8b82-bda4-11ed-9c8a-17c1eaa5b559
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 2.117.7
