version: 43.0.9
pageUuid: 238619aa-abac-11ed-ace6-5720e44455f5
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
      runtimeV2OptOut: false
  version: 2.117.7
  experimentalDataTabEnabled: true
