version: 43.0.9
pageUuid: e4ac775a-964e-11ed-b36e-138237f5b127
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 2.117.7
  experimentalDataTabEnabled: true
