version: 43.0.9
pageUuid: e492d888-104a-11ee-bef4-a71ec55151a0
appTemplate:
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 3.0.1
  experimentalDataTabEnabled: true
