version: 43.0.9
pageUuid: 79f11fca-a962-11ed-b5ba-8be31ff32ff3
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
      mobileOfflineModeDelaySync: false
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 2.117.7
  experimentalDataTabEnabled: true
